language: node_js
node_js:
- "0.12"

sudo: false

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli#develop
- cd /tmp
- chmod +x /home/travis/build/appdevdesigns/opstool-wordpress-plugin/test/setup/install.sh
- /home/travis/build/appdevdesigns/opstool-wordpress-plugin/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-wordpress-plugin .
- cd opstool-wordpress-plugin
- npm install

script:
- npm test
 
